-keepclasseswithmembers class com.jakewharton.disklrucache.DiskLruCache { *; }
-keepclasseswithmembers class com.jakewharton.disklrucache.DiskLruCache$Editor { *; }
-keepclasseswithmembers class com.jakewharton.disklrucache.DiskLruCache$Entry { *; }
